import { useEffect } from 'react'
import { BarChart3, Lightbulb, TrendingUp } from 'lucide-react'
import StableLink from '../stability/StableLink.tsx'
import { writeStabilityLog } from '../stability/linkStability'

const cards = [['Total sales', 'GBP 12,480.50'], ['Daily summary', 'GBP 416.02'], ['Weekly summary', 'GBP 2,912.14'], ['Monthly summary', 'GBP 12,480.50']] as const
export const salesContext = { totalSales: 12480.5, salesByProduct: [{ product: 'Classic Brew', revenue: 6420 }], salesByCustomer: [{ customer: 'Ava Carter', revenue: 2100 }], trend: 'up 18%', predictions: 'steady growth', anomalies: [], opportunities: ['Bundle Classic Brew with Trail Bottle'] }

export default function FounderSales() { useEffect(() => { writeStabilityLog('founder-insight', 'Sales dashboard context loaded', '/founder/sales') }, []); return <div className="space-y-8"><Header title="Sales Dashboard" description="Revenue performance, trends, predictions, and opportunities." /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value]) => <article key={label} className="rounded-xl border border-[#263238] bg-[#202C33] p-5"><BarChart3 className="text-[#6EE7A0]" size={21} /><p className="mt-5 text-sm text-gray-400">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></article>)}</div><div className="grid gap-5 lg:grid-cols-3"><Insight title="Sales by product" value="Classic Brew leads revenue at GBP 6,420." /><Insight title="Sales trends and predictions" value="Trend is up 18%; next period prediction is steady growth." /><Insight title="Sales anomalies and opportunities" value="No anomalies. Bundle Classic Brew with Trail Bottle." /></div><StableLink to="/founder/bob" className="inline-flex items-center gap-2 rounded-lg bg-[#0FA958] px-5 py-3 font-semibold text-white hover:bg-[#0C8A48]"><Lightbulb size={18} />Open Bob sales insights</StableLink></div> }
export function Header({ title, description }: { title: string; description: string }) { return <div><p className="text-sm font-semibold text-[#6EE7A0]">Founder commercial intelligence</p><h1 className="mt-1 text-3xl font-bold">{title}</h1><p className="mt-2 text-gray-300">{description}</p></div> }
export function Insight({ title, value }: { title: string; value: string }) { return <article className="rounded-xl border border-[#263238] bg-[#202C33] p-5"><TrendingUp className="text-[#6EE7A0]" size={20} /><h2 className="mt-4 font-semibold">{title}</h2><p className="mt-2 text-sm text-gray-300">{value}</p></article> }