import { FormEvent, useEffect, useState } from 'react'
import { AlertTriangle, Database, Download, FileText, Package, Play, Plus, RefreshCw, Search, Store } from 'lucide-react'
import { foundItApi, FoundItListing, FoundItMerchant, FoundItPlatform, FoundItRun } from '../api/foundit.ts'
import { useAuthStore } from '../state/authStore'

type Tab = 'platforms' | 'listings' | 'merchants' | 'runs'

export default function FounderFoundIt() {
  const user = useAuthStore((state) => state.user)
  const role = user?.operatorRole || user?.role
  const canManage = Boolean(user?.founder || role === 'founder' || role === 'founder_admin' || role === 'founder_master' || role === 'admin')
  const [tab, setTab] = useState<Tab>('platforms')
  const [platforms, setPlatforms] = useState<FoundItPlatform[]>([])
  const [listings, setListings] = useState<FoundItListing[]>([])
  const [merchants, setMerchants] = useState<FoundItMerchant[]>([])
  const [runs, setRuns] = useState<FoundItRun[]>([])
  const [status, setStatus] = useState<{ database?: string; scheduler?: string }>({})
  const [busy, setBusy] = useState('')
  const [notice, setNotice] = useState('')
  const [error, setError] = useState('')

  const load = async () => {
    setError('')
    try {
      const [statusResponse, platformResponse, listingResponse, merchantResponse, runResponse] = await Promise.all([foundItApi.status(), foundItApi.platforms(), foundItApi.listings(), foundItApi.merchants(), foundItApi.runs()])
      setStatus(statusResponse.data.data)
      setPlatforms(platformResponse.data.data)
      setListings(listingResponse.data.data)
      setMerchants(merchantResponse.data.data)
      setRuns(runResponse.data.data)
    } catch (requestError: any) {
      setError(requestError.response?.data?.error?.message || requestError.message || 'Unable to load Found IT')
    }
  }

  useEffect(() => { void load() }, [])

  const act = async (label: string, operation: () => Promise<unknown>) => {
    setBusy(label); setError(''); setNotice('')
    try { await operation(); setNotice(`${label} completed`); await load() }
    catch (requestError: any) { setError(requestError.response?.data?.error?.message || requestError.message || `${label} failed`) }
    finally { setBusy('') }
  }

  return <div className="space-y-7"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-[#6EE7A0]">Standalone circular-commerce company</p><h1 className="mt-1 text-3xl font-bold">Found IT</h1><p className="mt-2 max-w-3xl text-gray-300">UK free-item discovery, merchant intelligence, listing review, and controlled WROS onboarding export.</p></div><div className="flex gap-2"><Status label="PostgreSQL" value={status.database || 'checking'} /><Status label="Scheduler" value={status.scheduler || 'checking'} /></div></header>{error&&<div role="alert" className="flex gap-3 rounded-lg border border-red-800 bg-red-950/40 p-4 text-sm text-red-200"><AlertTriangle className="shrink-0" size={18}/><span>{error}</span></div>}{notice&&<p className="rounded-lg border border-[#23633F] bg-[#163C2A] p-3 text-sm text-[#6EE7A0]">{notice}</p>}<div className="flex flex-wrap gap-2 border-b border-[#263238] pb-3">{([['platforms','Platforms',Database],['listings','Listings',Package],['merchants','Merchants',Store],['runs','Logs & errors',FileText]] as const).map(([id,label,Icon])=><button key={id} type="button" onClick={()=>setTab(id)} className={`inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-semibold ${tab===id?'bg-[#0FA958] text-white':'bg-[#202C33] text-gray-300'}`}><Icon size={17}/>{label}</button>)}<button type="button" onClick={()=>void load()} className="ml-auto grid h-10 w-10 place-items-center rounded-lg bg-[#202C33]" aria-label="Refresh Found IT"><RefreshCw size={17}/></button></div>{tab==='platforms'&&<Platforms platforms={platforms} busy={busy} act={act} canManage={canManage}/>} {tab==='listings'&&<Listings listings={listings} busy={busy} act={act} canManage={canManage}/>} {tab==='merchants'&&<Merchants merchants={merchants} busy={busy} act={act} canManage={canManage}/>} {tab==='runs'&&<Runs runs={runs}/>}</div>
}

function Status({ label, value }: { label: string; value: string }) { return <span className="rounded-lg border border-[#34444A] bg-[#202C33] px-3 py-2 text-xs"><span className="text-gray-400">{label}</span> <strong className="ml-1 text-[#6EE7A0]">{value}</strong></span> }

function Platforms({ platforms, busy, act, canManage }: { platforms: FoundItPlatform[]; busy: string; act: (label: string, operation: () => Promise<unknown>) => Promise<void>; canManage: boolean }) {
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data=new FormData(event.currentTarget); void act('Add platform',()=>foundItApi.addPlatform({name:data.get('name'),baseUrl:data.get('baseUrl'),scrapeMethod:data.get('scrapeMethod'),config:{searchUrl:data.get('searchUrl')||undefined}})); event.currentTarget.reset() }
  return <div className={`grid gap-6 ${canManage?'xl:grid-cols-[1fr_360px]':''}`}><section className="overflow-hidden rounded-xl border border-[#263238] bg-[#202C33]"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-[#263238] p-4"><h2 className="font-semibold">Registered platforms</h2>{canManage&&<div className="flex gap-2"><button type="button" onClick={()=>void act('Database migration',()=>foundItApi.migrate())} disabled={Boolean(busy)} className="rounded-lg border border-[#3A4A50] px-3 py-2 text-sm">Run migration</button><button type="button" onClick={()=>void act('Scrape run',()=>foundItApi.run())} disabled={Boolean(busy)} className="inline-flex items-center gap-2 rounded-lg bg-[#0FA958] px-3 py-2 text-sm font-semibold"><Play size={16}/>Run all</button></div>}</div><div className="divide-y divide-[#263238]">{platforms.map((platform)=><div key={platform.id} className="flex flex-wrap items-center gap-4 p-4"><div className="min-w-0 flex-1"><p className="font-semibold">{platform.name}</p><p className="truncate text-xs text-gray-400">{platform.scrape_method} · {platform.base_url}</p></div>{canManage&&<><button type="button" onClick={()=>void act(`${platform.active?'Disable':'Enable'} ${platform.name}`,()=>foundItApi.updatePlatform(platform.id,{active:!platform.active}))} className={`rounded-full px-3 py-1 text-xs font-bold ${platform.active?'bg-[#163C2A] text-[#6EE7A0]':'bg-[#3A2626] text-red-200'}`}>{platform.active?'Active':'Paused'}</button><button type="button" onClick={()=>void act(`Scrape ${platform.name}`,()=>foundItApi.run(platform.id))} className="grid h-9 w-9 place-items-center rounded-lg border border-[#3A4A50]" aria-label={`Run ${platform.name}`}><Play size={15}/></button></>}</div>)}{platforms.length===0&&<p className="p-5 text-sm text-gray-400">Run the migration to seed supported platforms.</p>}</div></section>{canManage&&<form onSubmit={submit} className="space-y-4 rounded-xl border border-[#263238] bg-[#202C33] p-5"><div className="flex items-center gap-2 font-semibold"><Plus size={18} className="text-[#6EE7A0]"/>Register platform</div><Input name="name" label="Name" required/><Input name="baseUrl" label="Base URL" type="url" required/><Input name="searchUrl" label="Search URL (optional)" type="url"/><label className="grid gap-2 text-sm">Scrape method<select name="scrapeMethod" className="rounded-lg bg-[#2A3942] px-3 py-2" defaultValue="html"><option value="rss">RSS</option><option value="html">HTML</option><option value="playwright">Playwright</option><option value="ebay_api">eBay API</option></select></label><button disabled={Boolean(busy)} className="w-full rounded-lg bg-[#0FA958] px-4 py-2.5 font-semibold">Add platform</button></form>}</div>
}

function Listings({ listings, busy, act, canManage }: { listings: FoundItListing[]; busy: string; act: (label: string, operation: () => Promise<unknown>) => Promise<void>; canManage: boolean }) {
  const [editing, setEditing] = useState<FoundItListing|null>(null)
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data=new FormData(event.currentTarget); const payload={title:data.get('title'),description:data.get('description'),category:data.get('category'),url:data.get('url'),location:data.get('location'),merchantName:data.get('merchantName'),merchantUrl:data.get('merchantUrl')||data.get('url'),platform:data.get('platform')}; void act(editing?'Correct listing':'Add listing',()=>editing?foundItApi.updateListing(editing.id,payload):foundItApi.addListing(payload)); setEditing(null); event.currentTarget.reset() }
  return <div className={`grid gap-6 ${canManage?'xl:grid-cols-[1fr_360px]':''}`}><section className="overflow-x-auto rounded-xl border border-[#263238] bg-[#202C33]"><table className="min-w-full text-left text-sm"><thead className="border-b border-[#263238] text-xs uppercase text-gray-400"><tr><th className="p-4">Listing</th><th className="p-4">Source</th><th className="p-4">Location</th><th className="p-4">Status</th><th className="p-4">Actions</th></tr></thead><tbody className="divide-y divide-[#263238]">{listings.map((listing)=><tr key={listing.id}><td className="max-w-sm p-4"><a href={listing.url} target="_blank" rel="noreferrer" className="font-semibold text-[#6EE7A0]">{listing.title}</a><p className="mt-1 line-clamp-2 text-xs text-gray-400">{listing.description}</p></td><td className="p-4">{listing.platform}<p className="text-xs text-gray-400">{listing.merchant_name}</p></td><td className="p-4 text-gray-300">{listing.collection_location||'Unknown'}</td><td className="p-4">{listing.status}</td><td className="p-4"><div className="flex gap-2">{canManage&&<button type="button" onClick={()=>setEditing(listing)} className="rounded border border-[#3A4A50] px-2 py-1 text-xs">Correct</button>}<button type="button" disabled={Boolean(busy)} onClick={()=>void act('Export listing',()=>foundItApi.exportListing(listing.id))} className="grid h-8 w-8 place-items-center rounded bg-[#0FA958]" aria-label={`Export ${listing.title}`}><Download size={14}/></button></div></td></tr>)}{listings.length===0&&<tr><td colSpan={5} className="p-6 text-center text-gray-400">No listings collected yet.</td></tr>}</tbody></table></section>{canManage&&<form key={editing?.id||'new'} onSubmit={submit} className="space-y-4 rounded-xl border border-[#263238] bg-[#202C33] p-5"><div className="flex items-center gap-2 font-semibold"><Plus size={18} className="text-[#6EE7A0]"/>{editing?'Correct listing':'Manual listing'}</div><Input name="title" label="Title" defaultValue={editing?.title} required/><Input name="description" label="Description" defaultValue={editing?.description}/><Input name="category" label="Category" defaultValue={editing?.category||'free'}/>{!editing&&<><Input name="url" label="Listing URL" type="url" required/><Input name="merchantName" label="Merchant name" required/><Input name="merchantUrl" label="Merchant URL" type="url"/><Input name="platform" label="Platform" defaultValue="Manual" required/></>}<Input name="location" label="Collection location" defaultValue={editing?.collection_location}/><button className="w-full rounded-lg bg-[#0FA958] px-4 py-2.5 font-semibold">{editing?'Save correction':'Add listing'}</button>{editing&&<button type="button" onClick={()=>setEditing(null)} className="w-full text-sm text-gray-400">Cancel</button>}</form>}</div>
}

function Merchants({ merchants, busy, act, canManage }: { merchants: FoundItMerchant[]; busy: string; act: (label: string, operation: () => Promise<unknown>) => Promise<void>; canManage: boolean }) { const submit=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=new FormData(event.currentTarget);void act('Add merchant',()=>foundItApi.addMerchant({name:data.get('name'),platform:data.get('platform'),url:data.get('url'),location:data.get('location'),contactInfo:{email:data.get('email')}}));event.currentTarget.reset()}; return <div className={`grid gap-6 ${canManage?'xl:grid-cols-[1fr_360px]':''}`}><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{merchants.map((merchant)=><article key={merchant.id} className="rounded-xl border border-[#263238] bg-[#202C33] p-5"><Store className="text-[#6EE7A0]" size={20}/><a href={merchant.url} target="_blank" rel="noreferrer" className="mt-4 block font-semibold">{merchant.name}</a><p className="mt-1 text-sm text-gray-400">{merchant.platform} · {merchant.location||'Location unknown'}</p><div className="mt-4 flex items-center justify-between gap-3"><p className="text-xs text-gray-500">Last seen {new Date(merchant.last_seen).toLocaleString()}</p><button type="button" disabled={Boolean(busy)} onClick={()=>void act('Export merchant',()=>foundItApi.exportMerchant(merchant.id))} className="grid h-8 w-8 shrink-0 place-items-center rounded bg-[#0FA958]" aria-label={`Export ${merchant.name}`}><Download size={14}/></button></div></article>)}{merchants.length===0&&<p className="text-gray-400">No merchants collected yet.</p>}</div>{canManage&&<form onSubmit={submit} className="space-y-4 rounded-xl border border-[#263238] bg-[#202C33] p-5"><div className="flex items-center gap-2 font-semibold"><Plus size={18} className="text-[#6EE7A0]"/>Manual merchant</div><Input name="name" label="Name" required/><Input name="platform" label="Platform" defaultValue="Manual" required/><Input name="url" label="Profile URL" type="url" required/><Input name="email" label="Contact email" type="email"/><Input name="location" label="Location"/><button disabled={Boolean(busy)} className="w-full rounded-lg bg-[#0FA958] px-4 py-2.5 font-semibold">Add merchant</button></form>}</div> }

function Runs({ runs }: { runs: FoundItRun[] }) { return <div className="space-y-3">{runs.map((run)=><article key={run.id} className="flex flex-wrap items-start gap-4 rounded-xl border border-[#263238] bg-[#202C33] p-4"><Search className={run.status==='failed'?'text-red-400':'text-[#6EE7A0]'} size={19}/><div className="min-w-0 flex-1"><p className="font-semibold">{run.platform_name||'All platforms'} · {run.status}</p><p className="mt-1 text-sm text-gray-400">Seen {run.listings_seen} · Saved {run.listings_saved} · {new Date(run.started_at).toLocaleString()}</p>{run.error&&<p className="mt-2 text-sm text-red-300">{run.error}</p>}</div></article>)}{runs.length===0&&<p className="text-gray-400">No scrape runs recorded yet.</p>}</div> }

function Input({ label, name, type='text', defaultValue, required=false }: { label: string; name: string; type?: string; defaultValue?: string; required?: boolean }) { return <label className="grid gap-2 text-sm">{label}<input name={name} type={type} defaultValue={defaultValue} required={required} className="min-w-0 rounded-lg bg-[#2A3942] px-3 py-2 text-white"/></label> }