import { useMemo, useState } from 'react'
import { Film, Sparkles } from 'lucide-react'
import { founderApi } from '../api/founder'
import { getStabilityLogs, writeStabilityLog } from '../stability/linkStability'
import { salesContext } from './FounderSales'
import { marketingContext } from './FounderMarketing'
import { commercialContext } from './FounderCommercial'

const formats = ['Video script', 'Storyboard', 'Video outline', 'Voiceover script', 'Caption', 'Ad copy', 'Product promo', 'Marketing campaign', 'Email campaign', 'Landing page copy', 'Pitch deck', 'Commercial proposal', 'Social media content']
export default function FounderMediaStudio() { const [format, setFormat] = useState(formats[0]); const [brief, setBrief] = useState(''); const [output, setOutput] = useState(''); const context = useMemo(() => ({ sales: salesContext, marketing: marketingContext, commercial: commercialContext, systemLogs: getStabilityLogs().slice(-20), products: ['Classic Brew', 'Trail Bottle'], customers: ['Ava Carter', 'Noah Smith'] }), []); const generate = async () => { const prompt = `Generate a ${format} for this brief: ${brief || 'WROS retail growth'}\nStructured context: ${JSON.stringify(context)}`; try { const response = await founderApi.bobAsk(prompt); setOutput(response.data.data.reply); writeStabilityLog('founder-media', `${format} generated in Bob Media & Marketing Studio`, '/founder/bob/media') } catch (error) { setOutput(error instanceof Error ? error.message : 'Unable to generate content') } }; return <div className="space-y-7"><div><p className="text-sm font-semibold text-[#6EE7A0]">Founder content workspace</p><h1 className="mt-1 text-3xl font-bold">Bob Media &amp; Marketing Studio</h1><p className="mt-2 text-gray-300">Generate scripts, campaigns, commercial content, and launch assets from live founder context.</p></div><div className="grid gap-6 lg:grid-cols-[280px_1fr]"><aside className="rounded-xl border border-[#263238] bg-[#202C33] p-4"><div className="flex items-center gap-2 font-semibold"><Film size={18} className="text-[#6EE7A0]" />Content format</div><div className="mt-4 space-y-1">{formats.map((item) => <button key={item} type="button" onClick={() => setFormat(item)} className={`w-full rounded-lg px-3 py-2 text-left text-sm ${format === item ? 'bg-[#0FA958] text-white' : 'text-gray-300 hover:bg-[#2A3942]'}`}>{item}</button>)}</div></aside><section className="rounded-xl border border-[#263238] bg-[#202C33] p-5"><p className="text-sm text-gray-300">Selected format: <strong>{format}</strong></p><textarea value={brief} onChange={(event) => setBrief(event.target.value)} placeholder="Describe the campaign or asset Bob should create" className="mt-4 min-h-32 w-full rounded-lg bg-[#2A3942] p-3 text-sm text-white" /><button type="button" onClick={generate} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-[#0FA958] px-5 py-3 font-semibold hover:bg-[#0C8A48]"><Sparkles size={18} />Generate with Bob</button>{output && <pre className="mt-5 whitespace-pre-wrap rounded-lg bg-[#111B21] p-5 text-sm text-[#6EE7A0]">{output}</pre>}</section></div></div> }