import { FormEvent, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Lock, Mail } from 'lucide-react'
import { login } from '../api/auth'
import { useAuthStore } from '../state/authStore'
import { getErrorMessage } from '../utils/helpers'
import logo from '/wros-logo.svg'
import { getRoleHome } from '../utils/roleRoutes.ts'

export default function Login() { const navigate = useNavigate(); const save = useAuthStore((state) => state.login); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { const response = await login(email, password); const user = response.data.data.user; save(response.data.data.token, user); navigate(getRoleHome(user)) } catch (requestError) { setError(getErrorMessage(requestError, 'Unable to sign in')) } finally { setLoading(false) } }; return <AuthFrame title="Welcome back" subtitle="Sign in to your WROS workspace."><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-medium">Email<div className="relative mt-2"><Mail className="absolute left-3 top-3 text-gray-400" size={18} /><input className="w-full rounded-lg border border-gray-300 py-2.5 pl-10 pr-3 dark:border-gray-600 dark:bg-[#2A3942]" type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></div></label><label className="block text-sm font-medium">Password<div className="relative mt-2"><Lock className="absolute left-3 top-3 text-gray-400" size={18} /><input className="w-full rounded-lg border border-gray-300 py-2.5 pl-10 pr-3 dark:border-gray-600 dark:bg-[#2A3942]" type="password" value={password} onChange={(event) => setPassword(event.target.value)} required /></div></label>{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button type="submit" className="w-full rounded-lg bg-[#0FA958] py-3 font-semibold text-white transition-colors hover:bg-[#0C8A48]" disabled={loading}>{loading ? 'Signing in...' : 'Sign in'}</button><p className="text-center text-sm text-gray-500">New to WROS? <Link className="font-semibold text-[#0FA958]" to="/auth/signup">Create an account</Link></p><p className="text-center text-sm"><Link to="/" className="font-semibold text-[#0C8A48]">Return to Website</Link></p></form></AuthFrame> }

export function AuthFrame({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="grid min-h-screen place-items-center bg-gradient-to-br from-[#E7F5F3] via-white to-[#F0F2F5] p-5 dark:from-[#111B21] dark:via-[#202C33] dark:to-[#111B21]"><div className="w-full max-w-md rounded-2xl border border-gray-200 bg-white p-8 shadow-xl dark:border-[#263238] dark:bg-[#202C33]"><div className="mb-7 text-center"><img src={logo} alt="WROS" className="mx-auto mb-4 h-12 w-12 object-contain" /><h1 className="text-2xl font-bold">{title}</h1><p className="mt-2 text-sm text-gray-500 dark:text-gray-300">{subtitle}</p></div>{children}</div></div> }