import { useEffect, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import axiosClient from '../api/axiosClient'
import Loading from '../components/Loading.tsx'
import ComposeMessageModal from '../components/ComposeMessageModal.tsx'
import { Header } from './Orders.tsx'
import { getErrorMessage } from '../utils/helpers'
import FilterBar from '../components/FilterBar.tsx'
type Message={id:string;customerId:string;direction:string;text:string;status:string;timestamp:string}
export default function Messages(){const[messages,setMessages]=useState<Message[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[compose,setCompose]=useState(false);const[params,setParams]=useSearchParams();const[filters,setFilters]=useState({search:params.get('search')||'',direction:params.get('direction')||''});const load=()=>axiosClient.get<{data:Message[]}>('/mock/messages').then(r=>setMessages(r.data.data)).catch(e=>setError(getErrorMessage(e,'Unable to load messages'))).finally(()=>setLoading(false));useEffect(()=>{void load()},[]);useEffect(()=>setParams(Object.fromEntries(Object.entries(filters).filter(([,value])=>value)),{replace:true}),[filters,setParams]);const visible=messages.filter(m=>(!filters.direction||m.direction===filters.direction)&&(!filters.search||`${m.customerId} ${m.text}`.toLowerCase().includes(filters.search.toLowerCase())));return <section className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><Header eyebrow="Inbox" title="Messages" description="Inspect and filter message activity."/><button type="button" onClick={()=>setCompose(true)} className="rounded-lg bg-[#0FA958] px-4 py-2.5 font-semibold text-white">Compose Message</button></div><FilterBar fields={[{key:'search',label:'Search messages'},{key:'direction',label:'Direction',type:'select',options:['incoming','outgoing']}]} value={filters} onChange={next=>setFilters(next as typeof filters)}/><div className="overflow-hidden rounded-xl border border-[#EDEDED] bg-white shadow-sm dark:border-[#263238] dark:bg-[#202C33]">{loading?<Loading/>:error?<p className="p-5 text-sm text-red-600">{error}</p>:<div className="divide-y divide-[#EDEDED] dark:divide-[#263238]">{visible.map(message=><article key={message.id} className="p-5"><div className="flex items-center justify-between text-xs text-gray-500"><span>{message.customerId} · {message.direction}</span><span>{message.status}</span></div><p className="mt-2">{message.text}</p></article>)}</div>}</div>{compose&&<ComposeMessageModal onClose={()=>setCompose(false)} onSent={load}/>}</section>}
