import { ArrowRight, Bot, CheckCircle2, MessageSquare, ShieldCheck, Store } from 'lucide-react'
import { Link } from 'react-router-dom'

const features = [
  ['Conversational selling', 'Guide product discovery and move customer questions toward purchase.', MessageSquare],
  ['Merchant operations', 'Keep catalog, orders, customers, messaging, and automation in one workspace.', Store],
  ['BOB assistance', 'Get contextual support across public pages and authenticated consoles.', Bot],
  ['Tenant-safe access', 'Keep merchant data scoped while owner and founder controls remain separate.', ShieldCheck],
] as const

export function HomePage() {
  return <><section className="mx-auto grid min-h-[72vh] max-w-6xl items-center gap-10 px-5 py-16 lg:grid-cols-[1.15fr_.85fr]"><div><p className="text-sm font-bold uppercase tracking-widest text-[#0C8A48]">WhatsApp Retail OS</p><h1 className="mt-4 max-w-3xl text-5xl font-bold leading-tight md:text-6xl">Turn customer conversations into connected retail operations.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-gray-600 dark:text-gray-300">WROS brings selling, customer context, merchant workflows, and practical AI guidance into one focused system.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/auth/signup" className="inline-flex items-center gap-2 rounded-lg bg-[#0FA958] px-5 py-3 font-semibold text-white">Create Account <ArrowRight size={18}/></Link><Link to="/auth/login" className="rounded-lg border border-[#B9C8BF] bg-white px-5 py-3 font-semibold dark:border-[#3A4A50] dark:bg-[#202C33]">Login</Link></div></div><div className="border-l-4 border-[#0FA958] bg-white p-8 shadow-xl dark:bg-[#202C33]"><p className="text-sm font-semibold text-[#0FA958]">Built for focused teams</p><h2 className="mt-3 text-2xl font-bold">One operating layer, clear ownership.</h2><div className="mt-6 space-y-4">{['Public website stays public','Merchant work stays tenant-scoped','Owner controls stay cross-merchant','Founder tooling stays private'].map((item)=><p key={item} className="flex items-center gap-3"><CheckCircle2 className="text-[#0FA958]" size={20}/>{item}</p>)}</div></div></section><section id="features" className="border-y border-[#DDE5E0] bg-white py-16 dark:border-[#263238] dark:bg-[#172126]"><div className="mx-auto max-w-6xl px-5"><h2 className="text-3xl font-bold">A complete retail workflow</h2><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{features.map(([title, copy, Icon])=><article key={title} className="border border-[#DDE5E0] p-5 dark:border-[#34444A]"><Icon className="text-[#0FA958]"/><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-gray-600 dark:text-gray-300">{copy}</p></article>)}</div></div></section><section id="pricing" className="mx-auto max-w-6xl px-5 py-16"><h2 className="text-3xl font-bold">Start practical. Scale deliberately.</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{[['Starter','Core merchant workspace'],['Growth','Automation and team operations'],['Enterprise','Owner controls and deployment support']].map(([name,copy], index)=><article key={name} className={`border p-6 ${index===1?'border-[#0FA958] bg-[#EAF8EF] dark:bg-[#183328]':'border-[#DDE5E0] bg-white dark:border-[#34444A] dark:bg-[#202C33]'}`}><p className="font-bold text-[#0C8A48]">{name}</p><p className="mt-3 text-sm text-gray-600 dark:text-gray-300">{copy}</p><Link to="/contact" className="mt-6 inline-block font-semibold">Contact WROS</Link></article>)}</div></section></>
}

export function AboutPage() { return <PublicArticle eyebrow="About WROS" title="Retail clarity for messaging-first businesses."><p>WROS separates the public customer journey, merchant operations, owner oversight, and founder engineering controls so each audience sees only what they need.</p><p>BOB provides contextual assistance across the system while access controls protect tenant and platform boundaries.</p></PublicArticle> }
export function ContactPage() { return <PublicArticle eyebrow="Contact" title="Plan your WROS rollout."><p>Share the retail workflow, team structure, and customer journey you want to improve.</p><a className="inline-flex rounded-lg bg-[#0FA958] px-5 py-3 font-semibold text-white" href="mailto:info@wros.co.uk">Email info@wros.co.uk</a></PublicArticle> }
export function SupportPage() { return <PublicArticle eyebrow="Support" title="One place to get help."><p>For account access, merchant onboarding, data questions, or deployment support, contact the WROS support team.</p><div className="flex flex-wrap gap-3"><a className="rounded-lg bg-[#0FA958] px-5 py-3 font-semibold text-white" href="mailto:info@wros.co.uk">Contact Support</a><Link className="rounded-lg border border-[#B9C8BF] px-5 py-3 font-semibold dark:border-[#3A4A50]" to="/auth/login">Open your console</Link></div></PublicArticle> }

function PublicArticle({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <article className="mx-auto min-h-[68vh] max-w-4xl px-5 py-20"><p className="text-sm font-bold uppercase tracking-widest text-[#0C8A48]">{eyebrow}</p><h1 className="mt-4 text-4xl font-bold md:text-5xl">{title}</h1><div className="mt-8 space-y-6 text-lg leading-8 text-gray-600 dark:text-gray-300">{children}</div></article> }
