import { Link, Outlet } from 'react-router-dom'
import { useEffect, useState } from 'react'
import ThemeToggle from '../components/ThemeToggle.tsx'
import BobLite, { OPEN_BOB_LITE_EVENT, openBobLite } from '../public/BobLite.tsx'
import logo from '/wros-logo.svg'

export default function PublicLayout() {
  const [bobOpen, setBobOpen] = useState(false)
  useEffect(() => { const open = () => setBobOpen(true); window.addEventListener(OPEN_BOB_LITE_EVENT, open); return () => window.removeEventListener(OPEN_BOB_LITE_EVENT, open) }, [])
  return <div className="min-h-screen bg-[#F4F7F5] text-[#17211B] dark:bg-[#111B21] dark:text-white"><header className="sticky top-0 z-30 border-b border-[#DDE5E0] bg-white/95 backdrop-blur dark:border-[#263238] dark:bg-[#172126]/95"><div className="mx-auto flex min-h-18 max-w-6xl flex-wrap items-center justify-between gap-3 px-5 py-3"><Link to="/" className="flex items-center gap-3"><img src={logo} alt="WROS" className="h-11 w-11"/><span className="text-xl font-bold">WROS</span></Link><nav className="order-3 flex w-full items-center justify-center gap-4 overflow-x-auto text-sm font-semibold md:order-none md:w-auto md:gap-6"><Link to="/">Home</Link><Link to="/pricing">Pricing</Link><Link to="/about">About</Link><Link to="/contact">Contact</Link><Link to="/apply">Apply</Link></nav><div className="flex items-center gap-2"><ThemeToggle/><button type="button" onClick={openBobLite} className="hidden rounded-lg border border-[#0FA958] px-3 py-2 text-sm font-semibold text-[#0C8A48] lg:block">Chat with BOB</button><Link to="/auth/login" className="rounded-lg border border-[#0FA958] px-3 py-2 text-sm font-semibold text-[#0C8A48] sm:px-4">Login</Link></div></div></header><main><Outlet/></main><footer className="border-t border-[#DDE5E0] bg-white dark:border-[#263238] dark:bg-[#172126]"><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-5 py-8 text-sm"><span>WROS · Retail operations for conversational commerce.</span><div className="flex flex-wrap gap-5"><Link to="/about">About</Link><Link to="/contact">Contact</Link><Link to="/pricing">Pricing</Link><Link to="/support">Support</Link><a href="https://www.linkedin.com" aria-label="WROS on LinkedIn">LinkedIn</a><a href="https://www.instagram.com" aria-label="WROS on Instagram">Instagram</a></div></div></footer><button type="button" onClick={openBobLite} className="fixed bottom-5 right-5 z-40 grid h-14 w-14 place-items-center rounded-full bg-[#0FA958] text-xl font-bold text-white shadow-xl" aria-label="Chat with Bob AI">B</button><BobLite open={bobOpen} onClose={()=>setBobOpen(false)}/></div>
}
